In [1]:
import numpy as np

In [2]:
import numpy as up

In [3]:
import matplotlib.pyplot as plt

In [4]:
a = np.array([1,2,3]) #row vector = first order tensor

In [5]:
a.shape

(3,)

In [6]:
a = np.array([[1,2,3],[1,2,3]])

In [7]:
a.shape

(2, 3)

In [8]:
x = np.array([[1,2,3],
[3,2,1],
[2,1,1],
[1,1,2]])

In [9]:
x

array([[1, 2, 3],
       [3, 2, 1],
       [2, 1, 1],
       [1, 1, 2]])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [12]:
np.random.rand(2,3)

array([[0.32591386, 0.95052478, 0.26083074],
       [0.57261562, 0.98023746, 0.13581608]])

In [13]:
np.random.randn(2,3)

array([[-0.89828652,  0.1809003 ,  0.15011292],
       [ 0.28090235,  2.03160378, -0.34238863]])

In [14]:
A = np.array([1,2,3])

In [15]:
B = np.array([1,1,1])

In [16]:
A + B

array([2, 3, 4])

In [17]:
A - B

array([0, 1, 2])

In [18]:
A * B

array([1, 2, 3])

In [19]:
plt.plot(X[:,0],X[:,1],'ko')f

SyntaxError: invalid syntax (1469827712.py, line 1)